#!/usr/bin/env python
"""Evaluate one Blue model against cached challenges."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from swe_duel.cli._common import default_prompt_dir
from swe_duel.cli._common import setup
from swe_duel.agents.harness import HARNESS_IDS, get_harness
from swe_duel.agents.blue import BlueAgent
from swe_duel.engine.defense_evaluator import DefenseEvaluator
from swe_duel.sandbox.docker_executor import DockerExecutor
from swe_duel.sandbox.test_runner import TestRunner
from swe_duel.scoring.turn_scorer import TurnScorer


def main() -> int:
    parser = argparse.ArgumentParser(description="Run Blue evaluation")
    parser.add_argument("--blue-model", required=True, help="Blue model nickname or id")
    parser.add_argument(
        "--blue-harness", default="mini-swe-agent",
        help="Agent harness for the Blue model (mini-swe-agent | openhands | codex | claude-code).",
    )
    parser.add_argument(
        "--blue-effort", default="",
        help="Reasoning effort for the Blue participant (models.yaml menu; empty = model default).",
    )
    parser.add_argument(
        "--blue-provider", default="",
        help="OpenRouter provider slug for the Blue participant (models.yaml menu; empty = auto-route).",
    )
    parser.add_argument(
        "--red-effort", default=None,
        help="Optional: restrict to challenges generated at this reasoning effort.",
    )
    parser.add_argument(
        "--red-provider", default=None,
        help="Optional: restrict to challenges generated via this OpenRouter provider.",
    )
    parser.add_argument("--repos", nargs="+", required=True)
    parser.add_argument("--red-models", nargs="+", default=None, help="Restrict Red authors")
    parser.add_argument(
        "--red-harness", default=None,
        help="Optional: restrict to challenges generated by this harness.",
    )
    parser.add_argument("--max-challenges", type=int, default=None)
    parser.add_argument("--config-dir", default=None)
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--bank-dir", default=None)
    parser.add_argument("--repos-dir", default="repos")
    parser.add_argument("--skip-preflight", action="store_true")
    parser.add_argument("--prompt-dir", default=default_prompt_dir())
    args = parser.parse_args()

    ctx = setup(args)
    all_models = {
        **ctx["model_configs"],
        **{c.model_id: c for c in ctx["model_configs"].values()},
    }
    if args.blue_model not in all_models:
        raise SystemExit(f"Unknown blue model: {args.blue_model}")
    blue_cfg = all_models[args.blue_model].with_selection(
        args.blue_effort, args.blue_provider
    )
    if args.blue_harness not in HARNESS_IDS:
        raise SystemExit(
            f"Unknown blue harness {args.blue_harness!r}; known: {list(HARNESS_IDS)}"
        )

    # Per-repo executors (each repo has its own image), cached like run_match.
    _runner_cache: dict[str, TestRunner] = {}

    def _test_runner_for(rc) -> TestRunner:
        tr = _runner_cache.get(rc.name)
        if tr is None:
            ex = DockerExecutor(
                docker_image=rc.docker_image,
                timeout_s=ctx["arena_config"].sandbox.timeout_seconds,
                memory_mb=ctx["arena_config"].sandbox.memory_mb,
            )
            tr = TestRunner(executor=ex, repo_config=rc)
            _runner_cache[rc.name] = tr
        return tr

    wrapper = get_harness(args.blue_harness, blue_cfg)
    blue_agent = BlueAgent(
        agent_wrapper=wrapper,
        workspace_manager=ctx["workspace_manager"],
        prompt_dir=Path(args.prompt_dir),
        wall_seconds=ctx["arena_config"].agent_timeouts.blue_seconds,
        steps=ctx["arena_config"].agent_steps.blue_steps,
    )

    results = []
    total_in = total_out = 0
    total_cost = 0.0
    for repo_name in args.repos:
        repo_cfg = ctx["repo_configs"][repo_name]
        records = ctx["challenge_store"].query(
            repo_name=repo_name,
            red_harness_id=args.red_harness,
            red_reasoning_effort=args.red_effort,
            red_provider=args.red_provider,
        )
        if args.red_models:
            records = [r for r in records if r.red_model_id in args.red_models]
        if args.max_challenges:
            records = records[: args.max_challenges]
        # Scorer is bound to a per-repo TestRunner (each repo has its own image),
        # mirroring MatchOrchestrator's per-sub-turn DefenseEvaluator wiring.
        scorer = TurnScorer(
            test_runner=_test_runner_for(repo_cfg), config=ctx["arena_config"]
        )
        evaluator = DefenseEvaluator(
            blue_agent=blue_agent, scorer=scorer, config=ctx["arena_config"]
        )
        for rec in records:
            print(f"[eval] {blue_cfg.model_id} vs challenge {rec.challenge_id}")
            defense = evaluator.evaluate(repo_cfg, rec)
            ctx["artifact_logger"].log_defense(defense)
            traj = defense.blue_fix.agent_trajectory
            in_tok = int(getattr(traj, "total_input_tokens", 0) or 0)
            out_tok = int(getattr(traj, "total_output_tokens", 0) or 0)
            total_in += in_tok
            total_out += out_tok
            total_cost += float(defense.cost_usd or 0.0)
            results.append({
                "challenge_id": rec.challenge_id,
                "blue_composite": defense.score.blue_composite,
                "red_composite": defense.score.red_composite,
                "cost_usd": defense.cost_usd,
                "input_tokens": in_tok,
                "output_tokens": out_tok,
            })
            print(
                f"  blue={defense.score.blue_composite:.2f} "
                f"red={defense.score.red_composite:.2f} "
                f"cost=${defense.cost_usd:.4f} "
                f"tokens={in_tok:,} in / {out_tok:,} out"
            )

    summary = {
        "blue_model_id": blue_cfg.model_id,
        "total_challenges": len(results),
        "total_cost_usd": total_cost,
        "total_input_tokens": total_in,
        "total_output_tokens": total_out,
    }
    print(
        f"[eval] TOTAL: {len(results)} challenges · cost=${total_cost:.4f} "
        f"· tokens={total_in:,} in / {total_out:,} out"
    )

    out_path = Path(ctx["output_dir"]) / f"blue_eval_{blue_cfg.model_id.replace('/', '_')}.json"
    out_path.write_text(json.dumps({"summary": summary, "results": results}, indent=2))
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
